### ISSUE TITLE
KYC using Fingerprints

### ISSUE THREAD

**Issue by tdesai79** [khosla-labs/aadhaar-bridge#16]
Hi, we are trying to implement kyc/raw in android app using fingerprint. while going through following link https://github.com/khosla-labs/aadhaar-bridge/wiki/Supporting-Libraries-and-Services.
we came across supported devices.( Digital Persona ,Mantratec ,Iritech ,Safran Morphosmart MSO 1300). Does it mean that we can not implement fingerprint verification on normal android device which has inbuilt fingerprint recognition sensors? or in other words we can connect only the above listed/supported devices externally to android device for fingerprint based aadhaar verification?

**Comment by smutneja03** [comment]
There are two things that needs to be considered here. 

1. We provide an APK (AadhaarBridge.apk)that does biometric capture when one of the above mentioned devices are connected to the android device and also does the PID encryption of the personal  identity data present in the request. The devices you mentioned are required only if you are using the APK as the APK has the SDK of only these devices incorporated into it.
 
2. If you want to use to the device inbuilt fingerprint scanner, you can refer the [link](https://github.com/khosla-labs/aadhaar-bridge/wiki/Desktop%20Application#biometric-authentication-building-fingerprint-data) in order to compose the request and hit the gateway. Replace the raw biometrics here with the biometrics you will be getting from the device and things should work fine.

**Comment by saranya01adpay** [comment]
Hi,  we are tying to implement kyc in android app using aadhaar bridge of khosla labs, we bought the device Safran morpho mso 1300. The android app needs to capture the raw biometrics and send to our backend api. Backend API will follow the new KYC flow (user redirection for a consent).
Here i have implemented using the aua-packet creator lib jar. It requires raw biometrics. Kindly help us to capture raw biometrics from the device using android app.
