### ISSUE TITLE
Message no finger print device detected after entering aadhar number via sample app

### ISSUE THREAD

**Issue by asmsuchi** [khosla-labs/aadhaar-bridge#5]
Trying to test aadhar bridge as per instructions in github with the a samsung device(model # SM-G316HU) with Android version 4.4.4.
Connected the Morpho finger print scanner to android phone, installed android bridge and tried to launch via another sample as per instructions on your github website but the finger print scanner is not being recognized by the app.

Do we have to turn on any settings to make this work? How do we debug this issue?

**Comment by smutneja26** [comment]
Make sure you have these two applications installed in your android device, https://github.com/khosla-labs/aadhaar-bridge/tree/master/examples/AadhaarBridgeSamplerApp and https://github.com/khosla-labs/aadhaar-bridge/blob/master/libraries/AadhaarBridge.apk 

The sample app internally will be calling the apk in order to the biometric data capturing and pid encryption. 

Also, make sure you have the url of the gateway and environment you are accessing the service in configured in the sample app settings option.

**Comment by smutneja03** [comment]
As checked in person, things are now working fine with Android version 5.1.x and DigitalPersona device in place.
